name: Run Jupyter Notebook

on:
  push:
    branches:
      - main  # Adjust this as needed for your branch names
  workflow_dispatch:
  
jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Check out repository code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert ipykernel
        pip install ./src/requirements.txt
        pip install ComputationalHypergraphDiscovery
        # Install any other dependencies your notebook requires
        # For example: pip install numpy pandas matplotlib

    - name: Execute Jupyter notebook
      run: |
        jupyter nbconvert --to notebook --execute ./examples/algebraic_equations_graph_discovery.ipynb --output executed_example.ipynb

    - name: Upload executed notebook as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: executed_example.ipynb

